version:  '3.3'

services:
  webapp:
    image: juniperps/j-edi-web
    networks:
      - jedi
    volumes:
      - type: bind
        source: /data/robot/mns-oam
        target: /var/app/public/ostinato/output
    ports:
      - "9595:9595"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.backend=jedi
        - traefik.port=9595
        - "traefik.frontend.rule=PathPrefixStrip: /jedi"
        - traefik.docker.network=jedi
    env_file:
      - edi-web.env
networks:
  jedi:
    external: true
